//! `cargo run -p xtask -- vendor-fonts`
//!
//! Re-subsets the OFL font sources already present in `fonts-src/` (fetched
//! manually, once, per the README) into the WOFF2 files compiled into the
//! report-html build via `include_bytes!`, and rewrites
//! `assets/fonts/manifest.toml` with the resulting SHA-256 digests.
//!
//! Shells out to two locally installed tools — `hb-subset` (harfbuzz) and
//! `woff2_compress` (google/woff2) — neither of which is fetched here or by
//! any build script. Install them once with, e.g., `brew install harfbuzz
//! woff2` on macOS, or the equivalent `harfbuzz-tools`/`woff2` packages on
//! Linux.

use anyhow::{Context, bail};
use sha2::{Digest, Sha256};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Latin-range subset: printable ASCII (digits, upper/lower case, and every
/// ASCII punctuation mark the report emits as text) plus the en/em dashes
/// used in editorial copy. Deliberately excludes arrows, box-drawing, and
/// status-mark codepoints — those are SVG paths in the diagram generator,
/// never font glyphs.
const SUBSET_UNICODES: &str = "20-7E,2013,2014";

struct FontSpec {
    family: &'static str,
    weight: u16,
    source: &'static str,
    output: &'static str,
}

const FONTS: [FontSpec; 4] = [
    FontSpec {
        family: "Instrument Serif",
        weight: 400,
        source: "instrument-serif/InstrumentSerif-Regular.ttf",
        output: "instrument-serif-400-latin.woff2",
    },
    FontSpec {
        family: "Geist",
        weight: 400,
        source: "geist/Geist-Regular.ttf",
        output: "geist-400-latin.woff2",
    },
    FontSpec {
        family: "Geist",
        weight: 500,
        source: "geist/Geist-Medium.ttf",
        output: "geist-500-latin.woff2",
    },
    FontSpec {
        family: "Geist Mono",
        weight: 400,
        source: "geist-mono/GeistMono-Regular.ttf",
        output: "geist-mono-400-latin.woff2",
    },
];

pub fn run() -> anyhow::Result<()> {
    let workspace_root = workspace_root()?;
    let fonts_src = workspace_root.join("fonts-src");
    let assets_fonts = workspace_root
        .join("crates")
        .join("anne-de-breuil")
        .join("assets")
        .join("fonts");

    require_tool("hb-subset", &["--version"])?;
    require_tool("woff2_compress", &[])?;

    let tmp_dir = std::env::temp_dir().join(format!("anne-vendor-fonts-{}", std::process::id()));
    std::fs::create_dir_all(&tmp_dir)
        .with_context(|| format!("creating scratch dir {}", tmp_dir.display()))?;

    let mut manifest =
        String::from("# Generated by `cargo run -p xtask -- vendor-fonts`. Do not hand-edit.\n");

    for spec in &FONTS {
        let src_path = fonts_src.join(spec.source);
        if !src_path.is_file() {
            bail!(
                "missing font source {} — populate fonts-src/ first (see README)",
                src_path.display()
            );
        }

        let woff2_bytes = subset_to_woff2(&src_path, &tmp_dir, spec)?;
        if !woff2_bytes.starts_with(b"wOF2") {
            bail!(
                "{} did not produce a valid WOFF2 payload (missing wOF2 magic)",
                spec.output
            );
        }

        let out_path = assets_fonts.join(spec.output);
        std::fs::write(&out_path, &woff2_bytes)
            .with_context(|| format!("writing {}", out_path.display()))?;

        let digest = sha256_hex(&woff2_bytes);
        println!(
            "{} {} -> {} ({} bytes, sha256 {digest})",
            spec.family,
            spec.weight,
            spec.output,
            woff2_bytes.len()
        );

        let _ = writeln!(manifest, "\n[[font]]");
        let _ = writeln!(manifest, "family = {:?}", spec.family);
        let _ = writeln!(manifest, "weight = {}", spec.weight);
        let _ = writeln!(manifest, "file = {:?}", spec.output);
        let _ = writeln!(manifest, "sha256 = {digest:?}");
    }

    std::fs::remove_dir_all(&tmp_dir).ok();

    let manifest_path = assets_fonts.join("manifest.toml");
    std::fs::write(&manifest_path, manifest)
        .with_context(|| format!("writing {}", manifest_path.display()))?;
    println!("wrote {}", manifest_path.display());

    Ok(())
}

fn workspace_root() -> anyhow::Result<PathBuf> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .context("xtask crate must live one directory below the workspace root")
}

fn require_tool(name: &str, probe_args: &[&str]) -> anyhow::Result<()> {
    Command::new(name)
        .args(probe_args)
        .output()
        .with_context(|| {
            format!("`{name}` is not installed or not on PATH — see README for how to install it")
        })?;
    Ok(())
}

fn subset_to_woff2(src: &Path, tmp_dir: &Path, spec: &FontSpec) -> anyhow::Result<Vec<u8>> {
    let stem = spec.output.strip_suffix(".woff2").unwrap_or(spec.output);
    let subset_ttf = tmp_dir.join(format!("{stem}.ttf"));
    let subset_woff2 = tmp_dir.join(format!("{stem}.woff2"));

    let status = Command::new("hb-subset")
        .arg(src)
        .arg(format!("--unicodes={SUBSET_UNICODES}"))
        .arg("--no-hinting")
        .arg("--output-file")
        .arg(&subset_ttf)
        .status()
        .context("spawning hb-subset")?;
    if !status.success() {
        bail!("hb-subset failed subsetting {}", src.display());
    }

    let status = Command::new("woff2_compress")
        .arg(&subset_ttf)
        .status()
        .context("spawning woff2_compress")?;
    if !status.success() {
        bail!("woff2_compress failed converting {}", subset_ttf.display());
    }

    std::fs::read(&subset_woff2).with_context(|| format!("reading {}", subset_woff2.display()))
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    let mut hex = String::with_capacity(digest.len() * 2);
    for byte in digest {
        let _ = write!(hex, "{byte:02x}");
    }
    hex
}
